# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/maui"
site_name: MAUI

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock, controls/chart/how-to]
exclude_navigation: [knowledge-base/*]

navigation:
## List your directory names and order here, like this:
## Root Level
    get-started:
        title: "Getting Started"
        position: 1
    installation:
        title: "Installation"
        position: 2
    demos-and-sample-apps:
        title: "Sample Applications"
        position: 3
    controls:
        title: "Controls"
        position: 7
    troubleshooting:
        title: "Troubleshooting"
        position: 12
    "knowledge-base":
        title: "Knowledge Base"
        position: 14
## End Root Level
## Intallation Sub-Folders
    installation/windows:
        title: "Windows"
        position: 3
    installation/mac:
        title: "Mac"
        position: 4
## End Intallation Sub-Folders
## Controls Sub-Folders
    ## Accordion
    controls/accordion:
        title: "Accordion"
    ## End Accordion
    ## AutoComplete
    controls/autocomplete:
        title: "AutoComplete"
        ## AutoComplete Sub-Folders
    controls/autocomplete/templates:
        title: "Templates"
        position: 13
        ## End AutoComplete Sub-Folders
    ## End Barcode
    ## BadgeView
    controls/badgeview:
        title: "BadgeView"
    ## End BadgeView
    ## Barcode
    controls/barcode:
        title: "Barcode"
        ## Barcode Sub-Folders
    controls/barcode/1d-barcodes:
        title: "1D Barcodes"
        position: 5
    controls/barcode/2d-barcodes:
        title: "2D Barcodes"
        position: 6
        ## End Barcode Sub-Folders
    ## End Barcode
    ## Border
    controls/border:
        title: "Border"
    ## End Border
    ## BusyIndicator
    controls/busyindicator:
        title: "BusyIndicator"
    ## End BusyIndicator
    ## Button
    controls/button:
        title: "Button"
        ## Button Sub-Folders
    controls/button/howto:
        title: "How To"
        position: 6
        ## End Button Sub-Folders
    ## End Button
    ## Chart
    controls/chart:
        title: "Chart"
        ## Chart Sub-Folders
    controls/chart/types:
        title: "Chart Types"
        position: 3
    controls/chart/axes:
        title: "Axes"
        position: 4
    controls/chart/behaviors:
        title: "Behaviors"
        position: 6
    controls/chart/series:
        title: "Series"
        position: 5
            ## Chart Series Sub-Folders
    controls/chart/series/cartesian:
        title: "Cartesian Series"
        position: 2
                ## Chart Series CartesianSeries Sub-Folders
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 1
                ## End Chart Series CartesianSeries Sub-Folders
    controls/chart/series/pie:
        title: "Pie Series"
        position: 3
    controls/chart/series/financial:
        title: "Financial Series"
        position: 4
            ## End Chart Series Sub-Folders
    controls/chart/how-to:
        title: "How To"
        position: 11
        ## End Chart Sub-Folders
    ## End Chart
    ##CheckBox
    controls/checkbox:
        title: "CheckBox"
    ## End CheckBox
    ## ComboBox
    controls/combobox:
        title: "ComboBox"     
    ## End ComboBox
    ## DataForm
    controls/dataform:
        title: "DataForm"
    controls/dataform/editors:
        title: "Editors"
        position: 4
    controls/dataform/grouping:
        title: "Grouping"
        position: 6
    controls/dataform/layouts:
        title: "Layouts"
        position: 7
    controls/dataform/styling:
        title: "Styling"
        position: 15
    ## End DataForm
    ## DataGrid
    controls/datagrid:
        title: "DataGrid"
    controls/datagrid/columns:
        title: "Columns"
        position: 2
    controls/datagrid/aggregates:
        title: "Aggregates"
        position: 3
    controls/datagrid/columns/column-types:
        title: "Column Types"
        position: 1
    controls/datagrid/filtering:
        title: "Filtering"
        position: 3
    controls/datagrid/grouping:
        title: "Grouping"
        position: 4
    controls/datagrid/commands:
        title: "Commands"
        position: 10
    controls/datagrid/theming-and-styles:
        title: "Styling"
        position: 11
    ## End DataGrid
    ## DatePicker
    controls/datepicker:
        title: "DatePicker"
    controls/datepicker/styling:
        title: "Styling"
        position: 20
    ## End DatePicker
    ## DateTimePicker
    controls/datetimepicker:
        title: "DateTimePicker"
    controls/datetimepicker/styling:
        title: "Styling"
        position: 20
    ## End DateTimePicker
    ## DockLayout
    controls/docklayout:
        title: "DockLayout"
    ## End DockLayout
    ## Entry
    controls/entry:
        title: "Entry"
    ## End Entry
    ## Expander
    controls/expander:
        title: "Expander"
    ## End Expander
    ## Gauge
    controls/gauge:
        title: "Gauge"
        ## Gauge Sub-Folders
    controls/gauge/gauge-types:
        title: "Gauge Types"
        position: 2
        ## End Gauge Sub-Folders
    ## End Gauge
    ## ImageEditor
    controls/imageeditor:
        title: "ImageEditor"
        ## ImageEditor Sub-Folders
    controls/imageeditor/toolbar:
        title: "Toolbar"
        position: 4
        ## End ImageEditor Sub-Folders
    ## End ImageEditor
    ##ItemsControl
    controls/itemscontrol:
        title: "ItemsControl"
    ## End ItemsControl
    ## ListPicker
    controls/listpicker:
        title: "ListPicker"
    controls/listpicker/styling:
        title: "Styling"
        position: 20
    ## End ListPicker
    ## ListView
    controls/listview:
        title: "ListView"
        ## ListView Sub-Folders
    controls/listview/grouping:
        title: "Grouping"
        position: 4
    controls/listview/gestures:
        title: "Gestures"
        position: 11
    controls/listview/cells:
        title: Cells
        position: 2
    controls/listview/styling:
        title: "Styling"
        position: 14
    controls/listview/howto:
        title: "How To"
        position: 15
        ## End ListView Sub-Folders
    ## End ListView
    ## Map
    controls/map:
        title: "Map"
        ## Map Sub-Folders
    controls/map/layers:
        title: "Layers"
        position: 3
    controls/map/styling:
        title: "Styling"
        position: 9
        ## End Map Sub-Folders
    ## End Map
    ## MaskedEntry
    controls/maskedentry:
        title: "MaskedEntry"
        ## MaskedEntry Sub-Folders
    controls/maskedentry/mask-types:
        title: "Mask Types"
        position: 3
        ## End MaskedEntry Sub-Folders
    ## End MaskedEntry
    ## NumericInput
    controls/numericinput:
        title: "NumericInput"
    ## End NumericInput
    ## Path
    controls/path:
        title: "Path"
    ## End Path
    ## PdfProcessing
    controls/pdfprocessing:
        title: "PdfProcessing"
    ## End PdfProcessing   
    ## Popup
    controls/popup:
        title: "Popup"
    ## End Popup
    ## ProgressBar
    controls/progressbar:
        title: "ProgressBar"
    ## End ProgressBar
    ## Rating
    controls/rating:
        title: "Rating"
    ## End Rating
    ## SegmentedControl
    controls/segmentedcontrol:
        title: "SegmentedControl"
    ## End SegmentedControl
    ## SideDrawer
    controls/sidedrawer:
        title: "SideDrawer"
    ## End SideDrawer
    ## SignaturePad
    controls/signaturepad:
        title: "SignaturePad"
    ## End SignaturePad
    ## SpreadProcessing
    controls/spreadprocessing:
        title: "SpreadProcessing"
    ## End SpreadProcessing
    ## SpreadStreamProcessing
    controls/spreadstreamprocessing:
        title: "SpreadStreamProcessing"
    ## End SpreadStreamProcessing
    ## TabView
    controls/tabview:
        title: "TabView"
    ## End TabView
    ## TemplatedPicker
    controls/templatedpicker:
        title: "TemplatedPicker"
    controls/templatedpicker/styling:
        title: "Styling"
        position: 20
    ## End TemplatedPicker
    ## TimePicker
    controls/timepicker:
        title: "TimePicker"
    controls/timepicker/styling:
        title: "Styling"
        position: 20
    ## End TimePicker
    ## TimeSpanPicker
    controls/timespanpicker:
        title: "TimeSpanPicker"
    controls/timespanpicker/styling:
        title: "Styling"
        position: 20
    ## End TimeSpanPicker
    ## Toolbar
    controls/toolbar:
        title: "Toolbar"
    controls/toolbar/items:
        title: "Items"
        position: 4
    ## End Toolbar
    ## WordsProcessing
    controls/wordsprocessing:
        title: "WordsProcessing"    
    ## End WordsProcessing
    ## WrapLayout
    controls/wraplayout:
        title: "WrapLayout"
    ## End WrapLayout
    ## ZipLibrary
    controls/ziplibrary:
        title: "ZipLibrary"
    ## End ZipLibrary   
## End Controls Sub-Folders

## The application virtual path
baseurl: "/devtools/maui"

## The MVC Core version used
mvcCoreVersion: "2016.2.616"

## The product name
productName: "Telerik UI for .NET MAUI"
product: "Telerik UI for .NET MAUI"
platform: maui

api_reference_url: "api/"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Define any custom fields that you use in the site here
framework_name: MAUI

# Feedback Form Google Sheet ID
ff-sheet-id: 6ed4da75-840a-44ce-8832-ddf46f650e79

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '7eeef440dfb667c8a'
gcs_api_key: 'AIzaSyAF3UVKPTp93jQDEvt5iLqDfOwwrscqaok'

tabbed_code_marker_length: 3
tabbed_code_complex_separator: true

download: https://www.telerik.com/download/maui-ui
nav:
  "About": https://www.telerik.com/maui-ui

footer:
-
  title: "Sample Applications"
  links:
    "Controls Samples App": https://docs.telerik.com/devtools/maui/demos-and-sample-apps/controls-showcase-app
    "Crypto Tracker App": https://docs.telerik.com/devtools/maui/demos-and-sample-apps/crypto-app
-
  title: "Support Resources"
  links:
    ".NET MAUI SDKBrowser App": https://docs.telerik.com/devtools/maui/demos-and-sample-apps/sdkbrowser-app
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/maui
    "Blogs": https://www.telerik.com/blogs/mobile
    "Feedback Portal": https://feedback.telerik.com/maui
    "YouTube Channel": https://www.youtube.com/watch?v=3nInlHGsO8M&list=PLvmaC-XMqeBZnCAEuEcW9LsUnfQm65B1N&ab_channel=ProgressTelerik




footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/Telerik/

has_kb_portal: true
has_api_reference: true
has_cta_panels: true

intro_columns:
-
  categories:
  -
    title: "Data Controls"
    items:
      "DataForm": "dataform-overview"
      "DataGrid": "datagrid-overview"
      "ListView": "listview-overview"
      "ItemsControl": "itemscontrol-overview"
  -
    title: "Data Visualization"
    items:
        "Barcodes": "barcode-overview"
        "Charts": "chart-overview"
        "Gauges": "gauge-overview"
        "Map": "map-overview"
        "ProgressBar": "progressbar-overview"
        "Ratings": "rating-overview"
-
  categories:
  -
    title: "Editors"
    items:
        "AutoComplete": "autocomplete-overview"
        "ComboBox": "combobox-overview"
        "DatePicker": "datepicker-overview"
        "DateTimePicker": "datetimepicker-overview"
        "Entry": "entry-overview"
        "ImageEditor": "imageeditor-overview"
        "ListPicker": "listpicker-overview"
        "MaskedEntries": "maskedentry-overview"
        "NumericInput": "numericinput-overview"
        "TemplatedPicker": "templatedpicker-overview"
        "TimePicker": "timepicker-overview"
        "TimeSpanPicker": "timespanpicker-overview"
        "SignaturePad": "signaturepad-overview"
-
  categories:
  -
    title: "Navigation & Layouts"
    items:
        "Accordion": "accordion-overview"
        "DockLayout": "docklayout-overview"
        "Expander": "expander-overview"
        "SideDrawer": "sidedrawer-overview"
        "TabView": "tabview-overview"
        "WrapLayout": "wraplayout-overview"
  -
    title: "Buttons"
    items:
        "Segmented Control": "segmentedcontrol-overview"
        "Button": "button-overview"
        "CheckBox": "checkbox-overview"
-
  categories:
  -
    title: "Interactivity & UX"
    items:
        "BadgeView": "badgeview-overview"
        "Border": "border-overview"
        "BusyIndicator": "busyindicator-overview"
        "Path": "path-overview"
        "Popup": "popup-overview"
        "Toolbar": "toolbar-overview"
  -
    title: "Document Processing Libraries"
    items:
        "PdfProcessing": "pdfprocessing-overview"
        "WordsProcessing": "wordsprocessing-overview"
        "SpreadProcessing": "spreadprocessing-overview"
        "SpreadStreamProcessing": "spreadstreamprocessing-overview"
        "ZipLibrary": "ziplibrary-overview"

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
