# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/maui"
site_name: MAUI

# Exclude files which should not be in the output 
exclude: [README.md,Gemfile,Gemfile.lock, controls/chart/how-to]
exclude_navigation: [knowledge-base/*]

navigation:
## List your directory names and order here, like this:
## Root Level 
    demos-and-sample-apps:
        title: "Demos and Sample Apps"
        position: 2      
    controls:
        title: "<b>.NET MAUI Controls</b>"
        position: 7
    licensing:
        title: "Licensing"
        position: 9 
    troubleshooting:
        title: "Troubleshooting"
        position: 12
## End Root Level
## Controls Sub-Folders
    ## Barcode
    controls/barcode:
        title: "Barcode"
        ## Barcode Sub-Folders  
    controls/barcode/1d-barcodes:
        title: "1D Barcodes"
        position: 5
    controls/barcode/2d-barcodes:
        title: "2D Barcodes"
        position: 6        
        ## End Barcode Sub-Folders
    ## End Barcode   
    ## Border
    controls/border:
        title: "Border"
    ## End Border 
    ## BusyIndicator
    controls/busyindicator:
        title: "BusyIndicator"
    ## End BusyIndicator    
    ## Button
    controls/button:
        title: "Button"
        ## Button Sub-Folders
    controls/button/howto:
        title: "How To"
        position: 3
        ## End Button Sub-Folders
    ## End Button
    ## Chart
    controls/chart:
        title: "Chart"
        ## Chart Sub-Folders
    controls/chart/types:
        title: "Chart Types"
        position: 3
    controls/chart/axes:
        title: "Axes"
        position: 4
    controls/chart/behaviors:
        title: "Behaviors"
        position: 6
    controls/chart/series:
        title: "Series"
        position: 5
            ## Chart Series Sub-Folders
    controls/chart/series/cartesian:
        title: "CartesianSeries"
        position: 2
                ## Chart Series CartesianSeries Sub-Folders
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 1
                ## End Chart Series CartesianSeries Sub-Folders
    controls/chart/series/pie:
        title: "PieSeries"
        position: 3
    controls/chart/series/financial:
        title: "Financial Series"
        position: 4
            ## End Chart Series Sub-Folders
    controls/chart/how-to:
        title: "How To"
        position: 11
        ## End Chart Sub-Folders
    ## End Chart
    ##CheckBox
    controls/checkbox:
        title: "CheckBox"
    ## End CheckBox
    ## DataGrid
    controls/datagrid:
        title: "DataGrid"
    controls/datagrid/columns: 
        title: "Columns"
        position: 2
    controls/datagrid/columns/column-types: 
        title: "Column Types"
        position: 1    
    controls/datagrid/commands:
        title: "Commands"
        position: 9
    controls/datagrid/theming-and-styles: 
        title: "Styling"
        position: 10
    ## End DataGrid
    ## DatePicker
    controls/datepicker:
        title: "Date Picker"
    ## End DatePicker
    ## DockLayout
    controls/docklayout:
        title: "DockLayout"
    ## End DockLayout
    ## Entry
    controls/entry:
        title: "Entry"
    ## End Entry
    ## Gauge
    controls/gauge:
        title: "Gauge"
        ## Gauge Sub-Folders
    controls/gauge/gauge-types:
        title: "Gauge Types"
        position: 2
        ## End Gauge Sub-Folders
    ## End Gauge
    ##ItemsControl
    controls/itemscontrol:
        title: "ItemsControl"
    ## End ItemsControl
    ## ListPicker
    controls/listpicker:
        title: "List Picker"
    ## End ListPicker
    ## ListView
    controls/listview:
        title: "ListView"
        ## ListView Sub-Folders
    controls/listview/grouping:
        title: "Grouping"
        position: 4
    controls/listview/gestures:
        title: "Gestures"
        position: 11
    controls/listview/cells:
        title: Cells
        position: 2   
    controls/listview/styling:
        title: "Styling"
        position: 14         
    controls/listview/howto:
        title: "How To"
        position: 15
        ## End ListView Sub-Folders
    ## End ListView
    ## MaskedEntry
    controls/maskedentry:
        title: "MaskedEntry"
        ## MaskedEntry Sub-Folders
    controls/maskedentry/maskedtypes:
        title: "Masked Types"
        position: 3
        ## End MaskedEntry Sub-Folders
    ## End MaskedEntry
    ## NumericInput
    controls/numericinput:
        title: "NumericInput"
    ## End NumericInput
    ## Path
    controls/path:
        title: "Path"   
    ## End Path
    ## Popup
    controls/popup:
        title: "Popup"   
    ## End Popup
    ## Rating
    controls/rating:
        title: "Rating"    
    ## End Rating
    ## SegmentedControl
    controls/segmentedcontrol:
        title: "SegmentedControl"
    ## End SegmentedControl
    ## TemplatedPicker
    controls/templatedpicker:
        title: "Templated Picker"
    ## End TemplatedPicker
    ## TimePicker
    controls/timepicker:
        title: "Time Picker"
    ## End TimePicker
    ## TimeSpanPicker
    controls/timespanpicker:
        title: "TimeSpan Picker"
    ## End TimeSpanPicker
    ## WrapLayout
    controls/wraplayout:
        title: "WrapLayout"
    ## End WrapLayout       
## End Controls Sub-Folders

## The application virtual path
baseurl: "/devtools/maui"

## The MVC Core version used
mvcCoreVersion: "2016.2.616"

## The product name
productName: "Telerik UI for .NET MAUI"
product: "Telerik UI for .NET MAUI"
platform: maui

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        
# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Define any custom fields that you use in the site here
framework_name: MAUI

# Feedback Form Google Sheet ID
ff-sheet-id: 6ed4da75-840a-44ce-8832-ddf46f650e79

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '7eeef440dfb667c8a'
gcs_api_key: 'AIzaSyAF3UVKPTp93jQDEvt5iLqDfOwwrscqaok'

tabbed_code_marker_length: 3
tabbed_code_complex_separator: true

download: https://www.telerik.com/download/maui-ui
nav:
  "About": https://www.telerik.com/maui-ui

footer:

-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/maui
    "Blogs": https://www.telerik.com/blogs/mobile
    "Feedback Portal": https://feedback.telerik.com/maui
  

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

has_kb_portal: false
has_api_reference: false
has_cta_panels: false

intro_columns:
-
  categories:
  -
    title: "Data Controls"  
    items:
      "DataGrid": "datagrid-overview"
      "ListView": "listview-overview"
      "ItemsControl": "itemscontrol-overview"
  -
    title: "Data Visualization"
    items:
        "Barcode": "barcode-overview"
        "Charts": "chart-overview"
        "Gauge": "gauge-overview"
        "Rating": "rating-overview"
-
  categories:
  -   
    title: "Editors"
    items:        
        "Date Picker": "date-picker-overview"
        "Entry": "entry-overview"
        "List Picker": "list-picker-overview"
        "MaskedEntry": "maskedentry-overview"
        "NumericInput": "numericinput-overview"
        "Templated Picker": "templated-picker-overview"
        "Time Picker": "time-picker-overview"
        "TimeSpan Picker": "timespan-picker-overview"        
-
  categories:
  -
    title: "Layouts"
    items:
        "DockLayout": "docklayout-overview"
        "WrapLayout": "wraplayout-overview"
  -
    title: "Buttons"
    items:
        "Segmented Control": "segmentedcontrol-overview"
        "Button": "button-overview"
        "CheckBox": "checkbox-overview"
-
  categories:    
  - 
    title: "Interactivity & UX"
    items:
        "Border": "border-overview"
        "BusyIndicator": "busyindicator-overview"
        "Path": "path-overview"
        "Popup": "popup-overview"
        
        

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
